[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false



[font]
size = 18

[font.normal]
# family = "IosevkaTerm Nerd Font"
family = "JetBrainsMono Nerd Font"

[selection]
semantic_escape_chars = ''',│`|:"' ()[]{}<>'''

[window]
decorations = "full"
startup_mode = "Windowed"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 12
y = 12

[general]
live_config_reload = true
working_directory = "None"
import = ["/Users/nato/.config/alacritty/gruber_darker.yml"]
